### ISSUE TITLE
Fatal Error: NIOAny.swift, line 101

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#138] opened 2019-11-26 21:28 UTC
!!! this is a transferred, original issue: https://github.com/apple/swift-nio/issues/1270, original reporter @StrangeDays !!!

### Expected behavior

- Work like developed and running on OSX 
- All requests work

### Actual behavior

- Fatal error: tried to decode as type Request but found Request with contents other(AsyncHTTPClient.HTTPClient.Request(method:

- Fatal error: tried to decode as type ByteBuffer but found IOData with contents other(IOData

### Steps to reproduce

Run your Server on Linux via Docker (swift:latest, ...)

- https://github.com/IBM-Swift/Kitura/issues/1465

### If possible, minimal yet complete reproducer code (or URL to code)

Pretty simple RestRequest (SwiftyRequest) with responseObject and responseData

!!! issue transferred from https://github.com/apple/swift-nio/issues/1270, original reporter @StrangeDays !!!

### SwiftNIO version/commit hash

2.10.1

### Swift & OS version (output of `swift --version && uname -a`)

Swift version 5.1 (swift-5.1.2-RELEASE)
Target: x86_64-unknown-linux-gnu
Linux e965e14a2285 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by StrangeDays** [comment] 2019-11-30 11:25
I was able to make my Code work with following steps for a workaround -- if somebody needs a quick solution

- Rewrite vom `SwiftyRequest` to 'classic' `HTTP.request` 
- Use docker `swift:xenial` as `libcurl3` is used instead of `libcurl4`

BTW: compiling the newest libcurl4 with swift:latest didn't work with SwiftyRequest as well

**Comment by StrangeDays** [comment] 2019-11-30 11:28
I was able to make my Code work with following steps for a workaround -- if somebody needs a quick solution

- Rewrite vom `SwiftyRequest` to 'classic' `HTTP.request` 
- Use docker `swift:xenial` as `libcurl3` is used instead of `libcurl4`

BTW: compiling the newest libcurl4 with swift:latest didn't work with SwiftyRequest as well

**Comment by weissi** [comment] 2019-12-02 18:23
ping @artemredkin

**Comment by artemredkin** [comment] 2019-12-05 18:57
@StrangeDays hi, I'm having difficulties reproducing the crash, here is what I was trying to run:
```swift
import SwiftyRequest
import Dispatch

let request = RestRequest(method: .get, url: "http://google.com/")
let semaphore = DispatchSemaphore(value: 0)
request.responseData { result in
    switch result {
    case .success(let response):
        print(response.status)
    case .failure(let error):
        print(error)
    }
    semaphore.signal()
}
semaphore.wait()
```
running on:
```
$ uname -a
Linux swift-server-builder 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ swift --version
Swift version 5.1 (swift-5.1.2-RELEASE)
Target: x86_64-unknown-linux-gnu
$ dpkg -l | grep libcurl
ii  libcurl4:amd64                             7.58.0-2ubuntu3.8                               amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
```
Does this issue reproduce always or intermittenly? Can you show me what your workaround was about? It strange that using libcurl3 helped, we are not relying on it at all.

**Comment by StrangeDays** [comment] 2019-12-16 21:40
@artemredkin sry 4 responding so l8.
I need some notification strategy from regarding github ;-)

The first thing i notice is the using of DispatchSemaphore, which I don't use.
So I will check the usage of DispatchSemaphore in my code and respond asap.

**Comment by StrangeDays** [comment] 2020-01-18 17:14
@artemredkin -- finally i got time ;-) 
1st : The Bug is fixed in 1.0.1
2nd: I thing the issue is with connecting to an IP (eg. 127.0.0.1)
If you connect to an IP you should get crash with 1.0.0

**Comment by artemredkin** [comment] 2020-01-20 17:16
@StrangeDays glad to hear that. But I would prefer to reproduce this this crash so we can add a test to prevent this from happening. Should it be the same example as earlier but with an IP address? Is it just local host or any IP? Does it have to be https? Thank you!

**Comment by weissi** [comment] 2020-02-26 16:11
@StrangeDays / @artemredkin any updates here or can this be closed?

**Comment by artemredkin** [comment] 2020-02-26 17:52
I was unable to reproduce the issue unfortunately

**Comment by weissi** [comment] 2020-02-26 18:25
happy to close because @StrangeDays says it's fixed :)

**Closed** 2020-03-26 15:32 UTC
Labels: bug
