### ISSUE TITLE
Thread Sanitizer issues with release version of code

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/async-http-client#326] opened 2021-01-11 16:37 UTC
I was using AsyncHTTPClient to test another system and wanted to use the thread sanitizer but AHC keeps throwing up an issue when `IdlePoolConnectionHandler.channelInactive` is calling `HTTP1ConnectionProvider.remoteClosed`.

To verify the issue wasn't related to my work I ran the following in the async-http-client repository
```
swift test -c release --sanitize=thread -Xswiftc -enable-testing
```
There appear to be quite a number of issues, but this one is the most frequent. Interestingly there doesn't appear to be any issues when compiling debug

Here is the output
```
WARNING: ThreadSanitizer: data race (pid=25186)
  Write of size 8 at 0x7b3000001900 by thread T12 (mutexes: write M2004):
    #0 specialized _NativeDictionary._delete(at:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x176f4)
    #1 specialized Dictionary._Variant.removeValue(forKey:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x166d3)
    #2 HTTP1ConnectionProvider.closeAndDelete() ConnectionPool.swift:389 (async-http-clientPackageTests:x86_64+0x11e77)
    #3 HTTP1ConnectionProvider.execute(_:logger:) ConnectionPool.swift:268 (async-http-clientPackageTests:x86_64+0xbc12)
    #4 HTTP1ConnectionProvider.remoteClosed(connection:logger:) ConnectionPool.swift:377 (async-http-clientPackageTests:x86_64+0x1198b)
    #5 IdlePoolConnectionHandler.channelInactive(context:) Connection.swift:134 (async-http-clientPackageTests:x86_64+0x2e57)
    #6 protocol witness for _ChannelInboundHandler.channelInactive(context:) in conformance IdlePoolConnectionHandler <compiler-generated> (async-http-clientPackageTests:x86_64+0x32a3)
    #7 ChannelHandlerContext.invokeChannelInactive() ChannelPipeline.swift:1360 (async-http-clientPackageTests:x86_64+0x3a6806)
    #8 ByteToMessageHandler.channelInactive(context:) Codec.swift:669 (async-http-clientPackageTests:x86_64+0x3c0e2b)
    #9 protocol witness for _ChannelInboundHandler.channelInactive(context:) in conformance ByteToMessageHandler<A> <compiler-generated> (async-http-clientPackageTests:x86_64+0x3c0f59)
    #10 ChannelHandlerContext.invokeChannelInactive() ChannelPipeline.swift:1360 (async-http-clientPackageTests:x86_64+0x3a6806)
    #11 ChannelHandlerContext.invokeChannelInactive() ChannelPipeline.swift:1362 (async-http-clientPackageTests:x86_64+0x3a6827)
    #12 _ChannelInboundHandler.channelInactive(context:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x393231)
    #13 protocol witness for _ChannelInboundHandler.channelInactive(context:) in conformance HTTPClient.NWErrorHandler <compiler-generated> (async-http-clientPackageTests:x86_64+0x77ab9)
    #14 ChannelHandlerContext.invokeChannelInactive() ChannelPipeline.swift:1360 (async-http-clientPackageTests:x86_64+0x3a6806)
    #15 protocol witness for _ChannelInboundHandler.channelInactive(context:) in conformance ServerBootstrap.AcceptHandler <compiler-generated>:287 (async-http-clientPackageTests:x86_64+0x3931d1)
    #16 protocol witness for _ChannelInboundHandler.channelInactive(context:) in conformance BackPressureHandler <null>:2 (async-http-clientPackageTests:x86_64+0x394e69)
    #17 ChannelHandlerContext.invokeChannelInactive() ChannelPipeline.swift:1360 (async-http-clientPackageTests:x86_64+0x3a6806)
    #18 ChannelPipeline.fireChannelInactive() ChannelPipeline.swift:572 (async-http-clientPackageTests:x86_64+0x3a4700)
    #19 specialized StateManagedChannel.close0(error:mode:promise:) StateManagedChannel.swift:210 (async-http-clientPackageTests:x86_64+0x555a98)
    #20 protocol witness for ChannelCore.close0(error:mode:promise:) in conformance NIOTSConnectionChannel <compiler-generated> (async-http-clientPackageTests:x86_64+0x57c0f9)
    #21 specialized HeadChannelHandler.close(context:mode:promise:) ChannelPipeline.swift:1001 (async-http-clientPackageTests:x86_64+0x3ae222)
    #22 protocol witness for _ChannelOutboundHandler.close(context:mode:promise:) in conformance HeadChannelHandler <compiler-generated>:1000 (async-http-clientPackageTests:x86_64+0x3a8c79)
    #23 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1491 (async-http-clientPackageTests:x86_64+0x3a602a)
    #24 specialized _ChannelOutboundHandler.close(context:mode:promise:) ChannelHandler.swift:261 (async-http-clientPackageTests:x86_64+0x3944b2)
    #25 protocol witness for _ChannelOutboundHandler.close(context:mode:promise:) in conformance AcceptBackoffHandler <null>:2 (async-http-clientPackageTests:x86_64+0x393f29)
    #26 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1491 (async-http-clientPackageTests:x86_64+0x3a602a)
    #27 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1493 (async-http-clientPackageTests:x86_64+0x3a6052)
    #28 specialized _ChannelOutboundHandler.close(context:mode:promise:) ChannelHandler.swift:261 (async-http-clientPackageTests:x86_64+0x3944b2)
    #29 _ChannelOutboundHandler.close(context:mode:promise:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x393739)
    #30 protocol witness for _ChannelOutboundHandler.close(context:mode:promise:) in conformance HTTPRequestEncoder <compiler-generated> (async-http-clientPackageTests:x86_64+0x4b670c)
    #31 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1491 (async-http-clientPackageTests:x86_64+0x3a602a)
    #32 specialized _ChannelOutboundHandler.close(context:mode:promise:) ChannelHandler.swift:261 (async-http-clientPackageTests:x86_64+0x3944b2)
    #33 _ChannelOutboundHandler.close(context:mode:promise:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x393739)
    #34 protocol witness for _ChannelOutboundHandler.close(context:mode:promise:) in conformance <> ByteToMessageHandler<A> <null>:2 (async-http-clientPackageTests:x86_64+0x3943c9)
    #35 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1491 (async-http-clientPackageTests:x86_64+0x3a602a)
    #36 ChannelHandlerContext.invokeClose(mode:promise:) ChannelPipeline.swift:1493 (async-http-clientPackageTests:x86_64+0x3a6052)
    #37 ChannelPipeline.close(mode:promise:) ChannelPipeline.swift:642 (async-http-clientPackageTests:x86_64+0x3a0227)
    #38 Channel.close(mode:promise:) Channel.swift:209 (async-http-clientPackageTests:x86_64+0x390b03)
    #39 protocol witness for ChannelOutboundInvoker.close(mode:promise:) in conformance NIOTSConnectionChannel <compiler-generated> (async-http-clientPackageTests:x86_64+0x55705b)
    #40 specialized ChannelOutboundInvoker.close(mode:file:line:) ChannelInvoker.swift:154 (async-http-clientPackageTests:x86_64+0x39a223)
    #41 ChannelOutboundInvoker.close(mode:file:line:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x399c28)
    #42 closure #5 in HTTP1ConnectionProvider.close() ConnectionPool.swift:405 (async-http-clientPackageTests:x86_64+0x1356c)
    #43 partial apply for closure #5 in HTTP1ConnectionProvider.close() <compiler-generated> (async-http-clientPackageTests:x86_64+0x1f663)
    #44 thunk for @escaping @callee_guaranteed () -> (@owned EventLoopFuture<()>) <compiler-generated> (async-http-clientPackageTests:x86_64+0x2747)
    #45 partial apply for thunk for @escaping @callee_guaranteed () -> (@owned EventLoopFuture<()>) <compiler-generated> (async-http-clientPackageTests:x86_64+0x6ac1)
    #46 specialized closure #1 in EventLoopFuture.flatMap<A>(file:line:_:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x62181)
    #47 partial apply for specialized closure #1 in EventLoopFuture.flatMap<A>(file:line:_:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x6b17)
    #48 specialized closure #1 in EventLoopFuture._whenComplete(_:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x15332)
    #49 specialized closure #1 in EventLoopFuture._whenComplete(_:) <null>:2 (async-http-clientPackageTests:x86_64+0x22029)
    #50 specialized closure #1 in EventLoopFuture._whenComplete(_:) <null>:2 (async-http-clientPackageTests:x86_64+0x21f39)
    #51 partial apply for specialized closure #1 in EventLoopFuture._whenComplete(_:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x67df)
    #52 closure #1 in EventLoopFuture._whenComplete(_:)specialized partial apply <null>:2 (async-http-clientPackageTests:x86_64+0x6e83)
    #53 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (async-http-clientPackageTests:x86_64+0x311e2)
    #54 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x37c6)
    #55 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x37c6)

  Previous read of size 8 at 0x7b3000001900 by main thread:
    #0 specialized Collection.map<A>(_:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x7e76)
    #1 specialized HTTPClient.shutdown(requiresCleanClose:queue:_:) HTTPClient.swift:202 (async-http-clientPackageTests:x86_64+0x3e973)
    #2 HTTPClient.syncShutdown(requiresCleanClose:) HTTPClient.swift:147 (async-http-clientPackageTests:x86_64+0x310b3)
    #3 implicit closure #1 in $defer #1 () in HTTPClientInternalTests.testProxyStreaming() <compiler-generated> (async-http-clientPackageTests:x86_64+0xc1f9e)
    #4 partial apply for implicit closure #1 in $defer #1 () in HTTPClientInternalTests.testProxyStreaming() <compiler-generated> (async-http-clientPackageTests:x86_64+0xc6a9c)
    #5 thunk for @callee_guaranteed () -> (@error @owned Error) <compiler-generated> (async-http-clientPackageTests:x86_64+0x961b0)
    #6 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) <compiler-generated> (async-http-clientPackageTests:x86_64+0xc23b8)
    #7 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply <null>:2 (async-http-clientPackageTests:x86_64+0xd9b20)
    #8 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply <null>:2 (async-http-clientPackageTests:x86_64+0xd8b98)
    #9 @objc HTTPClientInternalTests.testProxyStreaming() <compiler-generated> (async-http-clientPackageTests:x86_64+0xb3ff0)
    #10 __invoking___ <null>:3 (CoreFoundation:x86_64h+0x6455b)

  Location is heap block of size 184 at 0x7b30000018c0 allocated by main thread:
    #0 __sanitizer_mz_malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x5277a)
    #1 _malloc_zone_malloc <null>:2 (libsystem_malloc.dylib:x86_64+0x1bdfd)
    #2 specialized _NativeDictionary.mutatingFind(_:isUnique:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x16833)
    #3 specialized Dictionary._Variant.setValue(_:forKey:) <compiler-generated> (async-http-clientPackageTests:x86_64+0x1648c)
    #4 closure #1 in ConnectionPool.getConnection(_:preference:taskEventLoop:deadline:setupComplete:logger:) ConnectionPool.swift:90 (async-http-clientPackageTests:x86_64+0x779f)
    #5 HTTPClient.execute<A>(request:delegate:eventLoop:deadline:logger:) HTTPClient.swift:542 (async-http-clientPackageTests:x86_64+0x34ce9)
    #6 HTTPClient.execute<A>(request:delegate:deadline:logger:) HTTPClient.swift:455 (async-http-clientPackageTests:x86_64+0x339d4)
    #7 HTTPClient.execute(request:deadline:logger:) HTTPClient.swift:401 (async-http-clientPackageTests:x86_64+0x3348d)
    #8 HTTPClient.execute(_:url:body:deadline:logger:) HTTPClient.swift:336 (async-http-clientPackageTests:x86_64+0x32897)
    #9 HTTPClient.post(url:body:deadline:logger:) HTTPClient.swift:261 (async-http-clientPackageTests:x86_64+0x320c4)
    #10 HTTPClient.post(url:body:deadline:) HTTPClient.swift:250 (async-http-clientPackageTests:x86_64+0x31fce)
    #11 HTTPClientInternalTests.testProxyStreaming() HTTPClientInternalTests.swift:186 (async-http-clientPackageTests:x86_64+0xb34be)
    #12 @objc HTTPClientInternalTests.testProxyStreaming() <compiler-generated> (async-http-clientPackageTests:x86_64+0xb3ff0)
    #13 __invoking___ <null>:3 (CoreFoundation:x86_64h+0x6455b)

  Mutex M2004 (0x7b1000011740) created at:
    #0 pthread_mutex_init <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2e913)
    #1 Lock.init() lock.swift:48 (async-http-clientPackageTests:x86_64+0x4a4ba4)
    #2 specialized HTTPClient.init(eventLoopGroupProvider:configuration:backgroundActivityLogger:) HTTPClient.swift:111 (async-http-clientPackageTests:x86_64+0x3de50)
    #3 HTTPClient.__allocating_init(eventLoopGroupProvider:configuration:backgroundActivityLogger:) HTTPClient.swift:92 (async-http-clientPackageTests:x86_64+0x30918)
    #4 HTTPClient.__allocating_init(eventLoopGroupProvider:configuration:) HTTPClient.swift:82 (async-http-clientPackageTests:x86_64+0x30856)
    #5 HTTPClientInternalTests.testProxyStreaming() HTTPClientInternalTests.swift:166 (async-http-clientPackageTests:x86_64+0xb3215)
    #6 @objc HTTPClientInternalTests.testProxyStreaming() <compiler-generated> (async-http-clientPackageTests:x86_64+0xb3ff0)
    #7 __invoking___ <null>:3 (CoreFoundation:x86_64h+0x6455b)

  Thread T12 (tid=30683246, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race <compiler-generated> in specialized _NativeDictionary._delete(at:)
```

**Comment by Lukasa** [comment] 2021-01-11 18:24
I believe this is a dupe of #318

**Closed by Lukasa** 2021-01-11 18:24 UTC
