### ISSUE TITLE
Fatal error: should not happen

### ISSUE THREAD

**Issue by weissi** [swift-server/async-http-client#249] opened 2020-06-13 20:39 UTC
https://github.com/swift-server/async-http-client/blob/238c65318103ba3f99b318de14a801f6e4767dbc/Sources/AsyncHTTPClient/ConnectionsState.swift#L232

this assertion can easily be hit by putting the following code into the `HTTPBinHandler`:

```swift
    func errorCaught(context: ChannelHandlerContext, error: Error) {
        context.close(promise: nil)
    }
```

and then running the tests. I believe this is a real error that is likely to happen.

**Comment by artemredkin** [comment] 2020-06-14 10:15
This is a duplicate of https://github.com/swift-server/async-http-client/issues/248

**Closed** 2020-06-14 10:15 UTC
Labels: bug, ⚠️ release blocker
